config/routes.rb
Rails.application.routes.draw do
  get 'match_history/show'
  get 'tictactoe/start'
  post 'tictactoe/start'
  resources :games
  root to: "tictactoe#start"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]
  # GET /games or /games.json
  def index
    if session[:player1] == "" || session[:player2] == ""
      session[:error_msg] = 'Player names are required'
      redirect_to controller: 'tictactoe', action: 'start'
    end
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:p1, :p2, :game_result)
    end
end

app/controllers/match_history_controller.rb
class MatchHistoryController < ApplicationController
  def show
    if session[:player1] == '' || session[:player2] == ''
      session[:error_msg] = 'Player names are required'
      redirect_to controller: 'tictactoe', action: 'start'
    end
    @game = Game.paginate(page: params[:page], per_page: 5)
  end
end

app/controllers/tictactoe_controller.rb
class TictactoeController < ApplicationController
  def start
    session[:player1] = ""
    session[:player2] = ""
    Game.all.delete_all

    if request.post?
      if params[:Player1_Name] == "" || params[:Player2_Name] == ""
        session[:error_msg] = "Please enter a name for both players"
        redirect_to :action => "start"
      else
        session[:error_msg] = ""
        session[:player1] = params[:Player1_Name]
        session[:player2] = params[:Player2_Name]
        redirect_to :controller => "games", :action => "index"
      end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/match_history_helper.rb
module MatchHistoryHelper
end

app/helpers/tictactoe_helper.rb
module TictactoeHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :p1 %>
    <%= form.text_field :p1 %>
  </div>

  <div class="field">
    <%= form.label :p2 %>
    <%= form.text_field :p2 %>
  </div>

  <div class="field">
    <%= form.label :game_result %>
    <%= form.number_field :game_result %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<nav>
  <center>
    <h1 id="sitename" style="font-family: 'Roboto Slab', serif; ">TIC TAC TOE</h1>
  </center>

  <center>
    <div class="menu" id="myMenu">
      <a href="/tictactoe/start" style="font-family: 'Roboto Slab', serif; "  onclick="return confirm('It will delete all Match History')">Home</a>
      <a href="/games" style="font-family: 'Roboto Slab', serif; " class="active" >Game</a>
      <a href="/match_history/show" style="font-family: 'Roboto Slab', serif; ">Match History</a>
      <a href="javascript:void(0);" class="icon" onclick="responsive_nav()">
        <i class="fa fa-bars"></i>
      </a>
    </div>
  </center>
</nav>
<div class="wrapper">
  <div id = "s1" class="cell" onclick="nextMove(this)"></div>
  <div id = "s2" class="cell" onclick="nextMove(this)"></div>
  <div id = "s3" class="cell" onclick="nextMove(this)"></div>
  <div id = "s4" class="cell" onclick="nextMove(this)"></div>
  <div id = "s5" class="cell" onclick="nextMove(this)"></div>
  <div id = "s6" class="cell" onclick="nextMove(this)"></div>
  <div id = "s7" class="cell" onclick="nextMove(this)"></div>
  <div id = "s8" class="cell" onclick="nextMove(this)"></div>
  <div id = "s9" class="cell" onclick="nextMove(this)"></div>
  <div id="message"></div>
  <center>
    <button id="restart_btn" class="btn btn-danger" onclick="restart()">Restart</button>
  </center>
</div>

<center>
<div class="scores">
  <div class="row">
    <div class="col p">
      <h4><span id="player1" style="font-family: 'Roboto Slab', serif;"><%= session[:player1] %></span><span class="char" style="font-family: 'Roboto Slab', serif;"> - X</span></h4>
      <h5 id="p1_score">0</h5>
    </div>
    <div class="col ties">
      <h4 style="font-family: 'Roboto Slab', serif;">Ties</h4>
      <h5 id="tie_score">0</h5>
    </div>
    <div class="col com">
      <h4><span id="player2" style="font-family: 'Roboto Slab', serif;"><%= session[:player2] %></span><span class="char" style="font-family: 'Roboto Slab', serif;"> - O</span></h4>
      <h5 id="p2_score">0</h5>
    </div>
  </div>
</div>

</center>

<script>

    var draw_audio = new Audio("http://soundbible.com/grab.php?id=1466&type=mp3");
    var applause = new Audio("http://soundbible.com/grab.php?id=1964&type=mp3");
    function game_start(){
        document.getElementById("restart_btn").style.display = 'none';
        document.turn = "X";
        if(Math.random()<0.5){
            document.turn="O";
        }
        if(sessionStorage.getItem("p1_score")!=null) {
            document.getElementById("p1_score").innerText = sessionStorage.getItem("p1_score");
        }
        else {
            document.getElementById("p1_score").innerText = 0;
        }
        if(sessionStorage.getItem("p2_score")!=null) {
            document.getElementById("p2_score").innerText = sessionStorage.getItem("p2_score");
        }
        else {
            document.getElementById("p2_score").innerText = 0;
        }
        if(sessionStorage.getItem("tie_score")!=null) {
            document.getElementById("tie_score").innerText = sessionStorage.getItem("tie_score");
        }
        else {
            document.getElementById("tie_score").innerText = 0;
        }

        draw_audio.pause();
        applause.pause();
        var i;
        for(i=1;i<=9;i++){
            clear(i);
        }
        document.winner=null;
        setMessage(document.turn + " gets to start");
    }
    document.winner = null;

    function setMessage(msg) {
        document.getElementById("message").innerText = msg;
    }

    function nextMove(square) {
        if(document.winner == null) {
            if (square.innerText == "") {
                square.classList.add(document.turn);
                square.innerText = document.turn;
                if (winner(document.turn)) {
                    setMessage(document.turn + " Won");
                    document.winner = document.turn;
                    var p1 = document.getElementById('player1').textContent;
                    var p2 = document.getElementById('player2').textContent;
                    var winner_name = (document.turn) == "X" ? p1 : p2;
                    if(document.winner == "X"){
                        document.getElementById("p1_score").innerText = parseInt(document.getElementById("p1_score").innerText) + 1;
                        sessionStorage.setItem("p1_score", document.getElementById("p1_score").innerText);
                    }
                    else{
                        document.getElementById("p2_score").innerText = parseInt(document.getElementById("p2_score").innerText) + 1;
                        sessionStorage.setItem("p2_score", document.getElementById("p2_score").innerText);
                    }
                    $.ajax({
                        url: "/games",
                        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
                        data: {game: {p1: p1,
                                p2: p2,
                                game_result: winner_name}},
                        type: "POST",
                        success: function(data){
                            console.log(data);
                            applause.play();
                            alert("Congratulations:  "+winner_name+", you won...");
                        },
                        error: function(data){
                            console.log(data);
                        }
                    });
                    document.getElementById("restart_btn").style.display = 'block';
                }
                else if(!checkDraw())
                  switchTurn();
                else{
                    draw_audio.play();
                    setMessage("Draw");
                    square.classList.add(document.turn);
                    square.innerText = document.turn;
                    document.getElementById("restart_btn").style.display = 'block';
                    document.getElementById("tie_score").innerText = parseInt(document.getElementById("tie_score").innerText) + 1;
                    sessionStorage.setItem("tie_score", document.getElementById("tie_score").innerText);
                    alert("Its a Draw");
                 }
            } else {
                setMessage("Area already taken");
                document.getElementById("restart_btn").style.display= 'block';
            }
        }
    }

    function switchTurn() {
        if (document.turn == "X") {
            document.turn = "O";
            setMessage("It's " + document.turn + "'s turn");
        } else {
            document.turn = "X";
            setMessage("It's " + document.turn + "'s turn")
        }
    }

    function winner(move) {
        var result = false;
        if (checkRow(1, 2, 3, move) ||
            checkRow(4, 5, 6, move) ||
            checkRow(7, 8, 9, move) ||
            checkRow(1, 4, 7, move) ||
            checkRow(2, 5, 8, move) ||
            checkRow(3, 6, 9, move) ||
            checkRow(1, 5, 9, move) ||
            checkRow(3, 5, 7, move)) {
            result = true;
        }
        return result;
    }
    function checkDraw(){
        var count = 0;
        for(var i=1;i<=9;i++){
            if(document.getElementById("s" +i).innerText!=""){
                count++;
            }

        }
        if(count == 9){

            return true;
        }
        return false;
    }
    function checkRow(a, b, c, move) {
        var result = false;
        if (getBox(a) == move && getBox(b) == move && getBox(c) == move) {
            result = true;
        }
        return result;
    }

    function getBox(number) {
        return document.getElementById("s" + number).innerText;
    }
    function clear(number){
        document.getElementById("s" + number).innerText="";
        document.getElementById("s" + number).classList.remove("X");
        document.getElementById("s" + number).classList.remove("O");
    }
    function restart(){
        game_start();
    }
</script>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>P1:</strong>
  <%= @game.p1 %>
</p>

<p>
  <strong>P2:</strong>
  <%= @game.p2 %>
</p>

<p>
  <strong>Game result:</strong>
  <%= @game.game_result %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tictactoe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css'>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@600&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body onload="game_start()">
    <%= yield %>
  </body>
</html>

app/views/match_history/show.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<body>
<center>
  <div class="menu" id="myMenu" style="margin-top: 5%">
    <a href="/tictactoe/start" style="font-family: 'Roboto Slab', serif; "  onclick="return confirm('It will delete all Match History')">Home</a>
    <a href="/games" style="font-family: 'Roboto Slab', serif; " >Game</a>
    <a href="/match_history/show" style="font-family: 'Roboto Slab', serif; "  class="active">Match History</a>
    <a href="javascript:void(0);" class="icon" onclick="responsive_nav()">
      <i class="fa fa-bars"></i>
    </a>
  </div>
</center>
</nav>
<div class="card rounded card_hist" >
  <div class="card-header">
    <h2 class="card-title d-flex justify-content-between mb-2">
      <span>Match History</span>
    </h2>
  </div>
  <div class="card-body">
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Match Id</th>
        <th>Winner</th>
      </tr>
      </thead>
      <tbody>
      <% @game.each do |game| %>
        <tr>
          <td><h6><%= game.id %></h6></td>
          <% if session[:player1] == game.game_result %>
              <td><h6 style="color: #d8345f"><%= game.game_result %></h6></td>
           <% else %>
            <td><h6 style="color: #588da8"><%= game.game_result %></h6></td>
            <%end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    </div>
  <div class="card-footer">
    <%= will_paginate @game, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    <h5>Overall Winner:  <%= Game.group(:game_result).order('game_result DESC').limit(1).pluck(:game_result).first %></h5>
  </div>
</div>
</center>
</body>

app/views/tictactoe/start.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<body>
<center>
  <center>
    <h1 id="sitename" style="font-family: 'Roboto Slab', serif; font-size: 50px; margin-top: 5% ">TIC TAC TOE</h1>
  </center>
  <div class ="card" style="width: 50%; margin-top:2%">
    <div class="card-header">
      <h5 class="card-title d-flex justify-content-between mb-2">
        <span>Before You Start</span>
      </h5>
      <p style="color:red"><%= session[:error_msg] %></p>
    </div>
    <div class="card-body">
      <%= form_with do |form| %>
        <div class="field">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroup-sizing-default">   <%= form.label "Player 1" %> </span>
            </div>
            <%= form.text_field :Player1_Name, class: 'form-control' %>
          </div>
        </div>

        <div class="field">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroup-sizing-default"> <%= form.label "Player 2" %></span>
            </div>
            <%= form.text_field :Player2_Name, class: 'form-control' %>
          </div>
        </div>
        </div>
        <div class ="card-footer">
          <div class="actions">
            <%= form.submit "Start Game", class: 'btn btn-success'%>
          </div>
        </div>
      <% end %>
      </div>
</center>
<p id="notice"></p>
</body>

<script>
  sessionStorage.clear();
</script>